### ISSUE TITLE
Button not displaying on PRs which are merged

### ISSUE THREAD

**Issue by itay** [tomasbjerre/pull-request-notifier-for-bitbucket#197]
We have a trigger that is configured like this:

![image](https://cloud.githubusercontent.com/assets/3266/22909326/4bb61cb8-f208-11e6-83b7-21bf1f17890a.png)

I can see the API returning it:
![image](https://cloud.githubusercontent.com/assets/3266/22909339/59248e7a-f208-11e6-927c-99c56b5dd366.png)

However, it's not being rendered:
![image](https://cloud.githubusercontent.com/assets/3266/22909349/6238a6fe-f208-11e6-96a4-2bd8f8448a51.png)

Any idea what might be happening?

**Comment by tomasbjerre** [comment]
Which version of Bitbucket Server is that?

**Comment by itay** [comment]
4.11.1

**Comment by tomasbjerre** [comment]
No errors in the console tab of developer tools?
Do you have other buttons that are working with 4.11.1?

**Comment by tomasbjerre** [comment]
Now I see it!

I just released 2.54 that changes the "state" label to "Ignore if". Which is what those 2 checkboxes does. They ignore the notification if the PR is merged/declined.

**Comment by ahadiwijaya** [comment]
@tomasbjerre Was the fix just the label? I tried changing the configuration by unchecking the "State" (="Ignore if") conditions, and the issue still persists - the button is not appearing for merged PRs.
<img width="840" alt="screen shot 2017-02-16 at 12 06 46 pm" src="https://cloud.githubusercontent.com/assets/10664045/23038776/0e7dc910-f440-11e6-8ae5-3bd150049313.png">

The button is not appearing for PRs that have been merged:
<img width="185" alt="screen shot 2017-02-16 at 12 05 28 pm" src="https://cloud.githubusercontent.com/assets/10664045/23038807/295e3242-f440-11e6-957d-3a9677e41a09.png">

However, it is appearing for non-merged PRs:
<img width="172" alt="screen shot 2017-02-16 at 12 08 25 pm" src="https://cloud.githubusercontent.com/assets/10664045/23038835/4eb166d6-f440-11e6-9d8b-30534991da7c.png">

And I can also see the API returning the button data:
<img width="521" alt="screen shot 2017-02-16 at 12 10 11 pm" src="https://cloud.githubusercontent.com/assets/10664045/23038911/92f96500-f440-11e6-84b0-b9cf1e5d8ba3.png">

**Comment by tomasbjerre** [comment]
Yes that was the only change.

Perhaps the problem is a conflict with the [Webhook to Jenkins plugin](https://marketplace.atlassian.com/plugins/com.nerdwin15.stash-stash-webhook-jenkins/server/overview). If you disable that plugin, does the button from this plugin show up correctly also for unmerged PR:s?

**Comment by ahadiwijaya** [comment]
@tomasbjerre I believe the Webhook to Jenkins plugin has always been disabled for the repository - do you know what else could affect this?

**Comment by tomasbjerre** [comment]
The "Trigger Notification" -button in your first screenshot, is that not from the Webhook to Jenkins plugin?

**Comment by ahadiwijaya** [comment]
I think it's from PR notifier (?) Please correct me if I'm wrong.

`WebFragments.addWebItemDescriptor({"completeModuleKey":"se.bjurr.prnfs.pull-request-notifier-for-stash:se.bjurr.prnfb.triggerbutton","key":"se.bjurr.prnfb.triggerbutton","moduleKey":"se.bjurr.prnfb.triggerbutton","params":{},"pluginKey":"se.bjurr.prnfs.pull-request-notifier-for-stash","location":"bitbucket.internal.pullrequest.toolbar.deprecated/bitbucket.pull-request.toolbar.actions","weight":50,"linkText":"Trigger Notification","styleClass":"triggerManualNotification"});`

This fragment appears both on the merged and non-merged PRs, but I only see it on merged PRs.

**Comment by tomasbjerre** [comment]
Ok I will probably have some time to look at this tomorrow. Thanks for the info!

**Comment by ahadiwijaya** [comment]
Thanks @tomasbjerre !

**Comment by tomasbjerre** [comment]
I just tried it with Webhook plugin and there is no conflict. It works for me.

And you have no errors in the console log?
There are no invisible or space chars in your filter regexp or text?

**Comment by tomasbjerre** [comment]
I have configuration like this:
```
curl -u admin:admin 'http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings/notifications' -H 'Content-Type: application/json; charset=UTF-8' -H 'Accept: application/json, text/javascript, */*; q=0.01'
```
Gives:
```
[{"filterRegexp":"Build AMI","filterString":"${BUTTON_TRIGGER_TITLE}","headers":[],"method":"GET","name":"Notification","triggerIfCanMerge":"NOT_CONFLICTING","triggerIgnoreStateList":[],"triggers":["BUTTON_TRIGGER"],"url":"http://localhost:7990/bitbucket/plugins/servlet/prnfb/admin","uuid":"0ba1a2fb-c6e9-48c0-848e-72bde5597402","postContentEncoding":"NONE"},{"headers":[],"method":"GET","name":"Notification","triggerIfCanMerge":"ALWAYS","triggerIgnoreStateList":[],"triggers":["RESCOPED_FROM","RESCOPED_TO"],"url":"http://localhost:80/?abc","uuid":"b1306a3a-5a87-4145-80b7-660bc986dd25","postContentEncoding":"NONE"}]
```

```
curl -u admin:admin 'http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings/buttons/repository/1/pullrequest/1' -H 'Content-Type: application/json; charset=UTF-8' -H 'Accept: application/json, text/javascript, */*; q=0.01'
```
Gives:
```
[{"buttonFormList":[],"buttonFormListString":"[]","name":"Build AMI","uuid":"54fa6576-1dd2-4443-989e-bdb6ca3a238c"}]
```

And that button is also shown in GUI. What do you get with these curl commands?

**Comment by tomasbjerre** [comment]
I read this issue a bit to quick. It must be a frontend issue. Very hard to investigate unless there is an error in the console view of Developer Tools. Any other plugins you have installed that might cause it?

**Comment by tomasbjerre** [comment]
The "Trigger Notification" is added here:
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/src/main/resources/atlassian-plugin.xml#L59

It is just a placeholder that should be removed immediately when the page loads:
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/src/main/resources/pr-triggerbutton.js#L208

If is not removed, I would suspect that:
* The javascript was never loaded, do you see in the resources tab in Developer Tools?
* Or that it crashed, that should be clear from the console tab in Developer Tools.

**Comment by ahadiwijaya** [comment]
Hi,

On both cases, I see:
<img width="361" alt="screen shot 2017-02-21 at 10 32 05 am" src="https://cloud.githubusercontent.com/assets/10664045/23178817/aa72ca4e-f820-11e6-97c5-ad22031cc3b2.png">

On the error console, I do not see any error corresponding to pr-triggerbutton resources. Does this imply that the function that executes the generation of the buttons on the UI was never called?

**Comment by tomasbjerre** [comment]
Strange... Do you have anyone there who knows some Javascript and can debug it? the pr-triggerbutton.js is not minified and can be debugged.

It should find a button, the one called "Trigger Button", remove it and add new buttons in its place.

**Comment by ahadiwijaya** [comment]
:'( Sure, I'll keep you updated once I find someone and find out what happened. Thanks!

**Comment by itay** [comment]
@tomasbjerre I was trying to debug it, but Bitbucket minifies it automatically so it's basically impossible to debug on our production instance.

**Comment by tomasbjerre** [comment]
Thanks for trying @itay =)

Maby try `-Datlassian.webresource.disable.minification=true`

https://developer.atlassian.com/docs/advanced-topics/supporting-minification-of-javascript-and-css-resources

**Comment by tomasbjerre** [comment]
Also, perhaps you can add the un-minified version from your local filesystem:

https://developers.google.com/web/tools/setup/setup-workflow

**Comment by itay** [comment]
Unfortunately this is production system with over 1000 users - we can't mess with it :)

**Comment by tomasbjerre** [comment]
But if you add [local pr-buttontrigger.js ](https://developers.google.com/web/tools/setup/setup-workflow) it will only affect you.

**Comment by itay** [comment]
Ah, I misread it. We can give it a shot.

**Comment by tomasbjerre** [comment]
@aepfli Are your buttons returned from the rest-service?
Did you also install/update any other plugin when moving from 2.55 to 2.57?

**Comment by aepfli** [comment]
@tomasbjerre besides the workzone plugin - this was the only plugin we updated!


buttons REST CALL
`
[
{
"buttonFormList": [],
"buttonFormListString": "[]",
"name": "trigger FeatureBuild",
"projectKey": "****",
"repositorySlug": "****",
"userLevel": "EVERYONE",
"uuid": "1f3d6cf3-fd62-4335-b28d-24b70471d5cb",
"confirmationText": "Build has been Triggered! dont hit the button twice"
}
]`

**Comment by aepfli** [comment]
imho: is this "version" related... if so, maybe deactivate the version for others... so they wont get that problem!

**Comment by tomasbjerre** [comment]
If I understand correctly. @itay had the problem in 2.53. @aepfli had it working in 2.55.

But that is something you can do to help. Try older versions and try to identify one introducing the problem.

**Comment by aepfli** [comment]
i am right now getting a frontend dev.. to take a look with me... but, we also just use the minified version, as we cant switch for 500 users atm... also i will issue a restart of stash at night... maybe the old "quick fix" will help :D 

but i will come back to this topic!

**Comment by tomasbjerre** [comment]
Great! Thanks :)

**Comment by aepfli** [comment]
okay so right now i am debugging this with the minified version, and chrome is helping a lot by pretty print...

strangely on page load there is no object ".triggerManualNotification" the array length is null... this is happening on the first time it steps into your js part...! 

i hope this some information helps a little...!
![2017-03-06_13h21_11](https://cloud.githubusercontent.com/assets/9987394/23609810/243bafea-0270-11e7-8709-e08605433d51.png)

**Comment by aepfli** [comment]
as i am not really familiar with plugin development, i found something which can be related!

i saw you changed the "definition" of the item, from web-item to client-web-item in https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/commit/d1ca3cd0d7c8ccd5b3a784f2a82c0b37d9a2e6a7

maybe those are still two different issues, and mine is related to my version 4.6.1 and the bug, which is explained in https://jira.atlassian.com/browse/BSERV-8896!

just some ideas! if i am on the wrong path, let me know!

**Comment by tomasbjerre** [comment]
A $buttonArea is saved here:
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/src/main/resources/pr-triggerbutton.js#L12

And here the triggerManualNotification is removed:
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/src/main/resources/pr-triggerbutton.js#L208

So do you have a $buttonArea? Perhaps p.append(u) is: https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/src/main/resources/pr-triggerbutton.js#L286

**Comment by aepfli** [comment]
i read your code, and i am pretty aware of when and where stuff gets loaded.

but when i use jquery to get an object with class "triggerManualNotification" during debugging, on line 12, i get an empty array! So this object is not there, at that moment!, and isnt for the whole time, on every breakpoint, i cant find this element! So there is at least the bug for my problem! that this i not in the html!

And as i am using an "older" version -> this may relates to my comment 5 minutes ago! and my findings

**Comment by tomasbjerre** [comment]
OK! Sounds very interesting. Thanks. I will have a closer look at this later today.

For the record, that triggerManualNotification class should have been added from this config:
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/src/main/resources/atlassian-plugin.xml#L60

**Comment by aepfli** [comment]
yeah and in this file you should add:
`web-resource key="fix-dependency-bug">
 <context>bitbucket.page.pullRequest.view</context>
 <dependency>com.atlassian.bitbucket.server.bitbucket-client-web-fragments:pull-request-header-more-location</dependency>
</web-resource>`

well i checked your project out, and did the change already (not tested) but i cant push to your project... not familiar with github so far. but will dig into it, and try to provide a pull request!

**Comment by tomasbjerre** [comment]
I released this in 2.58 now. Really hope it works, thanks a lot @aepfli !

Please confirm if it works for you!

**Comment by aepfli** [comment]
Hi! Sadly 2.58 did not work! But we downgraded to version 2.54 and everything is running smoothly again!

I will get a docker with bitbucket running today, and evaluate different versions of bitbucket and 2.58! At least I will try, can't promise anything :)

**Comment by tomasbjerre** [comment]
You may try 2.59.

@aepfli You do get the buttons from the REST resource tight?
http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings/buttons/repository/1/pullrequest/1

**Comment by tomasbjerre** [comment]
Actually, 2.60!

**Comment by tomasbjerre** [comment]
@aepfli @ahadiwijaya @itay did any of you try this? Is it solved?

**Comment by aepfli** [comment]
Tried today just for 5 min, did not work... But so far I had not time to debug...

**Comment by tomasbjerre** [comment]
Manually pasting [this line](https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/src/main/resources/pr-triggerbutton.js#L11) into the console and see what it evaluates to, would be interesting.

**Comment by aepfli** [comment]
Well right now I am 10 days out of office helping a junior team somewhere... So I will check after that!

**Comment by itay** [comment]
I also happen to be on holiday this week and next :)
